services:
  family-e-ink-dashboard:
    image: trcook/maginkdash:latest
    container_name: family-e-ink-dashboard
    restart: unless-stopped
    ports:
      - "5002:5000"
    environment:
      # - ICS_URL=moved to env file
      - DISPLAY_TZ=America/Chicago
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
